#pragma once

#define BROMINE_ERROR_SUCCESS         0x0000
#define BROMINE_ERROR_FUNCTION_FAILED 0x0001
#define BROMINE_ERROR_WIN32           0x0002

#define BROMINE_SUCCESS(x) (((DWORD)x)==BROMINE_ERROR_SUCCESS)
#define BROMINE_FAILED(x)  (((DWORD)x)!=BROMINE_ERROR_SUCCESS)
